# Generated by Django 3.1.1 on 2020-09-30 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名稱')),
                ('description', models.TextField(default='無', verbose_name='描述')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.SmallIntegerField(verbose_name='班級')),
                ('grade', models.SmallIntegerField(default=1, verbose_name='年級')),
                ('name', models.CharField(max_length=12, verbose_name='姓名')),
                ('number', models.SmallIntegerField(verbose_name='號碼')),
            ],
            options={
                'ordering': ['class_code'],
            },
        ),
        migrations.CreateModel(
            name='Course_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_order', models.SmallIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.students')),
            ],
            options={
                'ordering': ['course'],
            },
        ),
    ]
