# Generated by Django 3.1.1 on 2020-09-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['id'], 'verbose_name_plural': '課程'},
        ),
        migrations.AlterModelOptions(
            name='course_record',
            options={'ordering': ['course'], 'verbose_name_plural': '選課記錄'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['class_code'], 'verbose_name_plural': '學生'},
        ),
        migrations.AddField(
            model_name='course',
            name='name_code',
            field=models.CharField(default='Z', max_length=2, verbose_name='組別'),
        ),
    ]
