# Generated by Django 3.1.1 on 2020-10-01 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201001_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_record',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Group_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.course', verbose_name='課程')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.students', verbose_name='學生')),
            ],
        ),
    ]
