# Generated by Django 3.1.1 on 2020-10-01 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201001_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_record',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
