# Generated by Django 3.1.2 on 2020-10-03 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201001_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group_record',
            options={'ordering': ('student',), 'verbose_name_plural': '志願分組'},
        ),
        migrations.AlterField(
            model_name='group_record',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='登錄時間'),
        ),
        migrations.AlterField(
            model_name='students',
            name='number',
            field=models.IntegerField(verbose_name='學號'),
        ),
    ]
