# Generated by Django 3.1.2 on 2020-10-04 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201004_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_record',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_record_name_code', to='app.course', verbose_name='課程'),
        ),
    ]
