# Generated by Django 3.1.2 on 2020-10-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201004_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_record',
            name='class_code',
            field=models.CharField(default=0, max_length=6, verbose_name='班級'),
        ),
    ]
