# Generated by Django 3.1.2 on 2020-10-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_group_record_class_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_record',
            name='Course_order',
            field=models.SmallIntegerField(default=0, verbose_name='志願'),
        ),
    ]
