# Generated by Django 3.1.2 on 2020-10-14 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_group_record_course_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_record',
            old_name='Course_order',
            new_name='course_order',
        ),
    ]
